services:
  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports: 
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=@teste123
    depends_on:
      - postgres  

  postgres:
    image: postgres:15.8-alpine3.20
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=converter
  go_app_dev:
    build:  
      context: .
      dockerfile: DockerFile
    environment:
      DEBUG: "true"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONVERSION_EXCHANGE: "conversion_exchange"
      CONVERSION_QUEUE: "video_conversion_queue"
      CONVERSION_KEY: "conversion"
      CONFIRMATION_KEY: "finish-conversion" 
      CONFIRMATION_QUEUE: "finish_conversion_queue"
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  external-storage:
    external: true